### PR TITLE
fix: update for webpack 4

### LINKED ISSUE #25: Webpack 4 Support
**Description**
ejs-loader causes an error on Webpack 4 when using _webpack-contrib/html-webpack-plugin_.

**Config**

      new HtmlWebpackPlugin({
          template: `!!ejs-loader!src/main.html`,
          xhtml: true,
          inject: 'body',
          cordova: process.env.device_target !== undefined
      }),

**Log**

    ERROR in ./node_modules/ejs-loader!./src/main.html                                                
    Module build failed: TypeError: Cannot read property 'ejsLoader' of undefined

### PR DESCRIPTION
**Pull request by KnisterPeter**
this.options is not available in webpack4 so we check and return
an empty object instead.

Closes #25

### CODE REVIEW

**Comment by dmnsgn** [comment]
@okonet any chance this can be merged quickly?
It is currently blocking if we want Webpack 4 in conjunction with the widely used webpack-contrib/html-webpack-plugin .

**Comment by okonet** [comment]
@dmnsgn do you want to take over this repo and maintain it? I don't have much time to work on this now.

**Comment by KnisterPeter** [comment]
@okonet you could add @dmnsgn and me as well if you don't mind

**Comment by okonet** [comment]
BTW I'm planning to transfer it to webpack-contrib but I still wouldn't mind help.

**Comment by KnisterPeter** [comment]
Sure, always glad to help

**Comment by okonet** [comment]
I'll setup semantic release so you can collaborate without me blocking you.

**Comment by KnisterPeter** [comment]
@dmnsgn Do you like to review this change? Can I merge it as is?

**Comment by dmnsgn** [comment]
@KnisterPeter Go for it.

**Comment by okonet** [comment]
Please wait till semantic-release is in place

**Comment by dmnsgn** [comment]
We should probably update the README to reflect the fact that options is deprecated on Webpack 4.

**Comment by KnisterPeter** [comment]
@okonet sure
@dmnsgn This is not neccessary. Its just an internal change any all the configuration options will still work. Its just that internally `this.options` is not set anymore.

File: index.js [hunk 1]
```diff
@@ -4,7 +4,7 @@ var loaderUtils = require('loader-utils');
 module.exports = function(source) {
   this.cacheable && this.cacheable();
   var query = loaderUtils.parseQuery(this.query);
-  var options = this.options.ejsLoader || {};
+  var options = this.options ? this.options.ejsLoader || {} : {};
```
Comment (okonet) [inline index.js]: I'd prefer this to be a breaking change instead of trying to be backward compatible.

Comment (okonet) [inline index.js]: Also, ` || {} : {}` looks like code smell to me

**Comment by okonet** [comment]
Yes, please update README

**Comment by okonet** [comment]
Looks like semantic-release is running now. We could try merging this when it's updated.

File: index.js (hunk 1 above)
Comment (KnisterPeter) [reply index.js]: Can you explain why we should break and support one version for webpack 3 and one for webpack 4 if its not neccessary?

Comment (KnisterPeter) [reply index.js]: I'll update this to be more readable.

**Comment by KnisterPeter** [comment]
And just to be clear, `this.options` was deprecated with webpack 3. It is removed now.

File: index.js [hunk 2]
```diff
@@ -1,10 +1,17 @@
...
+    return context.options.ejsLoader;
+  }
+  return {};
+}
+
 module.exports = function(source) {
   this.cacheable && this.cacheable();
   var query = loaderUtils.parseQuery(this.query);
-  var options = this.options ? this.options.ejsLoader || {} : {};
+  var options = getOptions(this);
```
Comment (dmnsgn) [inline index.js]: What about using `getOptions` from [loader-utils](https://github.com/webpack/loader-utils#getoptions).

It seems to be the standard way of getting the options from the loader.
That would require updating the `loader-utils` dependency (0.2.7 to 1.1.0) and remove the need for `var query = loaderUtils.parseQuery(this.query);` as well.

Comment (KnisterPeter) [reply index.js]: We can do that in a second PR. I would love to have this out of the window fast.

Comment (dmnsgn) [reply index.js]: Yes what I suggest is definitely a bigger change

**Comment by amirhossein693** [comment]
Hi every one
After update ejs-loader and get latest changes, I have this issue

`ERROR in ./node_modules/html-webpack-plugin/lib/loader.js!./views/index.ejs
    Module build failed: SyntaxError: Unexpected token )
        at Function (<anonymous>)
        at /home/amirhossein/Projects/Farafan/node_modules/ejs-loader/node_modules/lodash/index.js:10809:16
        at /home/amirhossein/Projects/Farafan/node_modules/ejs-loader/node_modules/lodash/index.js:11082:21
        at /home/amirhossein/Projects/Farafan/node_modules/ejs-loader/node_modules/lodash/index.js:8152:31
        at Function.template (/home/amirhossein/Projects/Farafan/node_modules/ejs-loader/node_modules/lodash/index.js:10808:20)
        at Object.module.exports (/home/amirhossein/Projects/Farafan/node_modules/ejs-loader/index.js:23:20)`
